import { OpenLootCollection } from "../store";

const _localDb: any = {
	items: [
		{
			id: "9a972ae1-867e-45fa-9ddb-71df084ce878",
			userId: "9da13787-7509-4a83-9b0c-53b73acf4c6a",
			issuedId: 931,
			collection: "BT0",
			optionName: "space_exalted_small_0",
			status: "unlocked",
			name: "Exalted Small SPACE",
			description:
				"SPACE are expansions to your Personal Metaverse that come in different sizes and rarities. SPACE is needed to attach Utility NFTs such as Armories, Forges and Time Wardens that allow you to craft and upgrade cosmetic NFTs and Hourglasses. SPACE can also be decorated with NFTs that you will find in game. You can connect multiple SPACE together to customize the layout of your Personal Metaverse. A Small Exalted SPACE has 3 Exits that can be used to connect to other SPACE or Utility NFTs.",
			rarity: "exalted",
			imageUrl: "https://openloot-metadata.bigtime.gg/BT0/space_exalted_small_0.png",
			tags: ["space", "exalted", "small"],
			archetypeId: "BT0_space_exalted_small_0",
			archetypeParams: "0",
			maxIssuance: 6000,
			game: {
				id: "56a149cf-f146-487a-8a1c-58dc9ff3a15c",
				name: "Big Time",
				description:
					"Big Time is a free-to-play, multiplayer action RPG game that combines fast-action combat and adventure through time and space.",
				status: "active",
				extra: {
					developer: "Big Time Studios",
					discordUrl: "https://discord.com/invite/bigtime",
					supportUrl: "https://bigtimestudios.zendesk.com/",
					twitterUrl: "https://twitter.com/playbigtime",
					itemCategories: [
						{
							category: "armor",
							displayName: "Armor",
						},
						{
							category: "decorations",
							displayName: "Decorations",
						},
						{
							category: "mysterybox",
							displayName: "Mystery Boxes",
						},
						{
							category: "space",
							displayName: "SPACE",
						},
						{
							category: "title",
							displayName: "Titles",
						},
						{
							category: "pass",
							displayName: "VIP Passes",
						},
						{
							category: "weapons",
							displayName: "Weapons",
						},
						{
							category: "emote",
							displayName: "Emotes",
						},
						{
							category: "footstep",
							displayName: "Footsteps",
						},
					],
					officialWebsite: "https://bigtime.gg/",
				},
				createdAt: "2022-09-18T22:55:45.061Z",
				updatedAt: "2022-09-18T22:55:45.061Z",
				version: 1,
				slug: "big-time",
			},
			sellableAt: 1665697552833,
			extra: {},
		},
		{
			id: "1b39677b-9fbc-4ba5-93ca-055ea84daad4",
			userId: "9b166a48-369f-41bc-ade9-ed6e39d48fe8",
			issuedId: 2020,
			collection: "BT0",
			optionName: "Emote_Meditation",
			status: "in-game",
			name: "Meditation (Emote)",
			description: "I'm just taking a moment to center myself...and ignore the chaos around me",
			rarity: "uncommon",
			imageUrl: "https://openloot-metadata.bigtime.gg/BT0/Emote_Meditation.png",
			tags: ["cosmetics", "emote"],
			archetypeId: "BT0_Emote_Meditation",
			archetypeParams: "0",
			maxIssuance: 6000,
			game: {
				id: "56a149cf-f146-487a-8a1c-58dc9ff3a15c",
				name: "Big Time",
				description:
					"Big Time is a free-to-play, multiplayer action RPG game that combines fast-action combat and adventure through time and space.",
				status: "active",
				extra: {
					developer: "Big Time Studios",
					discordUrl: "https://discord.com/invite/bigtime",
					supportUrl: "https://bigtimestudios.zendesk.com/",
					twitterUrl: "https://twitter.com/playbigtime",
					itemCategories: [
						{ category: "armor", displayName: "Armor" },
						{ category: "decorations", displayName: "Decorations" },
						{ category: "mysterybox", displayName: "Mystery Boxes" },
						{ category: "space", displayName: "SPACE" },
						{ category: "title", displayName: "Titles" },
						{ category: "pass", displayName: "VIP Passes" },
						{ category: "weapons", displayName: "Weapons" },
						{ category: "emote", displayName: "Emotes" },
						{ category: "footstep", displayName: "Footsteps" },
					],
					officialWebsite: "https://bigtime.gg/",
				},
				createdAt: "2022-09-18T22:55:45.061Z",
				updatedAt: "2022-09-18T22:55:45.061Z",
				version: 1,
				slug: "big-time",
			},
			sellableAt: 1677268246402,
			extra: {},
		},
		{
			id: "05751352-d27b-4dd7-b353-30b97685dcef",
			userId: "9da13787-7509-4a83-9b0c-53b73acf4c6a",
			issuedId: 1334,
			collection: "BT0",
			optionName: "BlackRed_2H_Hammer",
			status: "unlocked",
			name: "War Hammer of Sir Branor",
			description: "Weapon of Sir Branor known as the Dragon Knight.",
			rarity: "uncommon",
			imageUrl: "https://openloot-metadata.bigtime.gg/BT0/BlackRed_2H_Hammer.png",
			tags: ["cosmetic", "blackred", "weapons", "hammer"],
			archetypeId: "BT0_BlackRed_2H_Hammer",
			archetypeParams: "0",
			maxIssuance: 3500,
			game: {
				id: "56a149cf-f146-487a-8a1c-58dc9ff3a15c",
				name: "Big Time",
				description:
					"Big Time is a free-to-play, multiplayer action RPG game that combines fast-action combat and adventure through time and space.",
				status: "active",
				extra: {
					developer: "Big Time Studios",
					discordUrl: "https://discord.com/invite/bigtime",
					supportUrl: "https://bigtimestudios.zendesk.com/",
					twitterUrl: "https://twitter.com/playbigtime",
					itemCategories: [
						{
							category: "armor",
							displayName: "Armor",
						},
						{
							category: "decorations",
							displayName: "Decorations",
						},
						{
							category: "mysterybox",
							displayName: "Mystery Boxes",
						},
						{
							category: "space",
							displayName: "SPACE",
						},
						{
							category: "title",
							displayName: "Titles",
						},
						{
							category: "pass",
							displayName: "VIP Passes",
						},
						{
							category: "weapons",
							displayName: "Weapons",
						},
						{
							category: "emote",
							displayName: "Emotes",
						},
						{
							category: "footstep",
							displayName: "Footsteps",
						},
					],
					officialWebsite: "https://bigtime.gg/",
				},
				createdAt: "2022-09-18T22:55:45.061Z",
				updatedAt: "2022-09-18T22:55:45.061Z",
				version: 1,
				slug: "big-time",
			},
			sellableAt: 1665697552833,
			extra: {},
		},
		{
			id: "3d6df7fd-d146-489e-93d9-714c6c4d25b8",
			userId: "9b166a48-369f-41bc-ade9-ed6e39d48fe8",
			issuedId: 378,
			collection: "BT0",
			optionName: "Deco_Egyptian_SpecimenTable01",
			status: "unlocked",
			name: "Egyptian Specimen Table",
			description: "A small table upon which various Egyptian artifacts have been placed",
			rarity: "rare",
			imageUrl: "https://openloot-metadata.bigtime.gg/BT0/Deco_Egyptian_SpecimenTable01.png",
			tags: ["decorations", "egyptian", "table"],
			archetypeId: "BT0_Deco_Egyptian_SpecimenTable01",
			archetypeParams: "0",
			maxIssuance: 1000,
			game: {
				id: "56a149cf-f146-487a-8a1c-58dc9ff3a15c",
				name: "Big Time",
				description:
					"Big Time is a free-to-play, multiplayer action RPG game that combines fast-action combat and adventure through time and space.",
				status: "active",
				extra: {
					developer: "Big Time Studios",
					discordUrl: "https://discord.com/invite/bigtime",
					supportUrl: "https://bigtimestudios.zendesk.com/",
					twitterUrl: "https://twitter.com/playbigtime",
					itemCategories: [
						{ category: "armor", displayName: "Armor" },
						{ category: "decorations", displayName: "Decorations" },
						{ category: "mysterybox", displayName: "Mystery Boxes" },
						{ category: "space", displayName: "SPACE" },
						{ category: "title", displayName: "Titles" },
						{ category: "pass", displayName: "VIP Passes" },
						{ category: "weapons", displayName: "Weapons" },
						{ category: "emote", displayName: "Emotes" },
						{ category: "footstep", displayName: "Footsteps" },
					],
					officialWebsite: "https://bigtime.gg/",
				},
				createdAt: "2022-09-18T22:55:45.061Z",
				updatedAt: "2022-09-18T22:55:45.061Z",
				version: 1,
				slug: "big-time",
			},
			sellableAt: 1671056987058,
			extra: {},
		},
		{
			id: "e53c1978-58b6-464e-8fe8-69f0616ee550",
			userId: "9da13787-7509-4a83-9b0c-53b73acf4c6a",
			issuedId: 1624,
			collection: "BT0",
			optionName: "Chrome_2H_Hammer",
			status: "unlocked",
			name: "War Hammer of Sir Uriens",
			description: "Weapon of Sir Uriens known as the Angry Knight.",
			rarity: "uncommon",
			imageUrl: "https://openloot-metadata.bigtime.gg/BT0/Chrome_2H_Hammer.png",
			tags: ["cosmetic", "chrome", "weapons", "hammer"],
			archetypeId: "BT0_Chrome_2H_Hammer",
			archetypeParams: "0",
			maxIssuance: 3500,
			game: {
				id: "56a149cf-f146-487a-8a1c-58dc9ff3a15c",
				name: "Big Time",
				description:
					"Big Time is a free-to-play, multiplayer action RPG game that combines fast-action combat and adventure through time and space.",
				status: "active",
				extra: {
					developer: "Big Time Studios",
					discordUrl: "https://discord.com/invite/bigtime",
					supportUrl: "https://bigtimestudios.zendesk.com/",
					twitterUrl: "https://twitter.com/playbigtime",
					itemCategories: [
						{
							category: "armor",
							displayName: "Armor",
						},
						{
							category: "decorations",
							displayName: "Decorations",
						},
						{
							category: "mysterybox",
							displayName: "Mystery Boxes",
						},
						{
							category: "space",
							displayName: "SPACE",
						},
						{
							category: "title",
							displayName: "Titles",
						},
						{
							category: "pass",
							displayName: "VIP Passes",
						},
						{
							category: "weapons",
							displayName: "Weapons",
						},
						{
							category: "emote",
							displayName: "Emotes",
						},
						{
							category: "footstep",
							displayName: "Footsteps",
						},
					],
					officialWebsite: "https://bigtime.gg/",
				},
				createdAt: "2022-09-18T22:55:45.061Z",
				updatedAt: "2022-09-18T22:55:45.061Z",
				version: 1,
				slug: "big-time",
			},
			sellableAt: 1665697552833,
			extra: {},
		},
		{
			id: "955743fc-7a73-4d29-9938-a97672cb493e",
			userId: "9da13787-7509-4a83-9b0c-53b73acf4c6a",
			issuedId: 313,
			collection: "BT0",
			optionName: "Lightning_1H_Sword",
			status: "in-game",
			name: "Battle Blade of Sir Lancelot",
			description: "Weapon of Sir Lancelot known as the Proud Knight.",
			rarity: "epic",
			imageUrl: "https://openloot-metadata.bigtime.gg/BT0/Lightning_1H_sword.png",
			tags: ["cosmetic", "lightning", "weapons", "chopper"],
			archetypeId: "BT0_Lightning_1H_Sword",
			archetypeParams: "0",
			maxIssuance: 350,
			game: {
				id: "56a149cf-f146-487a-8a1c-58dc9ff3a15c",
				name: "Big Time",
				description:
					"Big Time is a free-to-play, multiplayer action RPG game that combines fast-action combat and adventure through time and space.",
				status: "active",
				extra: {
					developer: "Big Time Studios",
					discordUrl: "https://discord.com/invite/bigtime",
					supportUrl: "https://bigtimestudios.zendesk.com/",
					twitterUrl: "https://twitter.com/playbigtime",
					itemCategories: [
						{
							category: "armor",
							displayName: "Armor",
						},
						{
							category: "decorations",
							displayName: "Decorations",
						},
						{
							category: "mysterybox",
							displayName: "Mystery Boxes",
						},
						{
							category: "space",
							displayName: "SPACE",
						},
						{
							category: "title",
							displayName: "Titles",
						},
						{
							category: "pass",
							displayName: "VIP Passes",
						},
						{
							category: "weapons",
							displayName: "Weapons",
						},
						{
							category: "emote",
							displayName: "Emotes",
						},
						{
							category: "footstep",
							displayName: "Footsteps",
						},
					],
					officialWebsite: "https://bigtime.gg/",
				},
				createdAt: "2022-09-18T22:55:45.061Z",
				updatedAt: "2022-09-18T22:55:45.061Z",
				version: 1,
				slug: "big-time",
			},
			sellableAt: 1665697552833,
			extra: {},
		},
		{
			id: "bcbebed4-fa77-4639-9947-70ea5dd40201",
			userId: "9da13787-7509-4a83-9b0c-53b73acf4c6a",
			issuedId: 281,
			collection: "BT0",
			optionName: "FixerSingleEye_Head",
			status: "in-game",
			name: "Apprentice Prototype Head",
			description: "Early Prototype Fixer Armor designed by Ben Franklin at Evermore.",
			rarity: "rare",
			imageUrl: "https://openloot-metadata.bigtime.gg/BT0/FixerSingleEye_Head.png",
			tags: ["cosmetic", "fixersingleeye", "armor", "head"],
			archetypeId: "BT0_FixerSingleEye_Head",
			archetypeParams: "0",
			maxIssuance: 1000,
			game: {
				id: "56a149cf-f146-487a-8a1c-58dc9ff3a15c",
				name: "Big Time",
				description:
					"Big Time is a free-to-play, multiplayer action RPG game that combines fast-action combat and adventure through time and space.",
				status: "active",
				extra: {
					developer: "Big Time Studios",
					discordUrl: "https://discord.com/invite/bigtime",
					supportUrl: "https://bigtimestudios.zendesk.com/",
					twitterUrl: "https://twitter.com/playbigtime",
					itemCategories: [
						{
							category: "armor",
							displayName: "Armor",
						},
						{
							category: "decorations",
							displayName: "Decorations",
						},
						{
							category: "mysterybox",
							displayName: "Mystery Boxes",
						},
						{
							category: "space",
							displayName: "SPACE",
						},
						{
							category: "title",
							displayName: "Titles",
						},
						{
							category: "pass",
							displayName: "VIP Passes",
						},
						{
							category: "weapons",
							displayName: "Weapons",
						},
						{
							category: "emote",
							displayName: "Emotes",
						},
						{
							category: "footstep",
							displayName: "Footsteps",
						},
					],
					officialWebsite: "https://bigtime.gg/",
				},
				createdAt: "2022-09-18T22:55:45.061Z",
				updatedAt: "2022-09-18T22:55:45.061Z",
				version: 1,
				slug: "big-time",
			},
			sellableAt: 1665697552833,
			extra: {},
		},
		{
			id: "dc4d5070-454d-4970-8937-8d7cf8bcdd2c",
			userId: "9da13787-7509-4a83-9b0c-53b73acf4c6a",
			issuedId: 22,
			collection: "BT0",
			optionName: "Darkness_2H_Hammer",
			status: "locked",
			name: "War Hammer of Sir Brunor",
			description: "Weapon of Sir Brunor known as the Black Knight.",
			rarity: "legendary",
			imageUrl: "https://openloot-metadata.bigtime.gg/BT0/Darkness_2H_Hammer.png",
			tags: ["cosmetic", "darkness", "weapons", "hammer"],
			archetypeId: "BT0_Darkness_2H_Hammer",
			archetypeParams: "0",
			maxIssuance: 100,
			game: {
				id: "56a149cf-f146-487a-8a1c-58dc9ff3a15c",
				name: "Big Time",
				description:
					"Big Time is a free-to-play, multiplayer action RPG game that combines fast-action combat and adventure through time and space.",
				status: "active",
				extra: {
					developer: "Big Time Studios",
					discordUrl: "https://discord.com/invite/bigtime",
					supportUrl: "https://bigtimestudios.zendesk.com/",
					twitterUrl: "https://twitter.com/playbigtime",
					itemCategories: [
						{
							category: "armor",
							displayName: "Armor",
						},
						{
							category: "decorations",
							displayName: "Decorations",
						},
						{
							category: "mysterybox",
							displayName: "Mystery Boxes",
						},
						{
							category: "space",
							displayName: "SPACE",
						},
						{
							category: "title",
							displayName: "Titles",
						},
						{
							category: "pass",
							displayName: "VIP Passes",
						},
						{
							category: "weapons",
							displayName: "Weapons",
						},
						{
							category: "emote",
							displayName: "Emotes",
						},
						{
							category: "footstep",
							displayName: "Footsteps",
						},
					],
					officialWebsite: "https://bigtime.gg/",
				},
				createdAt: "2022-09-18T22:55:45.061Z",
				updatedAt: "2022-09-18T22:55:45.061Z",
				version: 1,
				slug: "big-time",
			},
			sellableAt: 1665697552833,
			extra: {},
		},
		{
			id: "15e0cae4-9525-4395-9d9d-a0d8b05deb38",
			userId: "9da13787-7509-4a83-9b0c-53b73acf4c6a",
			issuedId: 650,
			collection: "BT0",
			optionName: "Chrome_2H_Axe",
			status: "unlocked",
			name: "Battle Axe of Sir Uriens",
			description: "Weapon of Sir Uriens known as the Angry Knight.",
			rarity: "uncommon",
			imageUrl: "https://openloot-metadata.bigtime.gg/BT0/Chrome_2H_Axe.png",
			tags: ["cosmetic", "chrome", "weapons", "axe"],
			archetypeId: "BT0_Chrome_2H_Axe",
			archetypeParams: "0",
			maxIssuance: 3500,
			game: {
				id: "56a149cf-f146-487a-8a1c-58dc9ff3a15c",
				name: "Big Time",
				description:
					"Big Time is a free-to-play, multiplayer action RPG game that combines fast-action combat and adventure through time and space.",
				status: "active",
				extra: {
					developer: "Big Time Studios",
					discordUrl: "https://discord.com/invite/bigtime",
					supportUrl: "https://bigtimestudios.zendesk.com/",
					twitterUrl: "https://twitter.com/playbigtime",
					itemCategories: [
						{
							category: "armor",
							displayName: "Armor",
						},
						{
							category: "decorations",
							displayName: "Decorations",
						},
						{
							category: "mysterybox",
							displayName: "Mystery Boxes",
						},
						{
							category: "space",
							displayName: "SPACE",
						},
						{
							category: "title",
							displayName: "Titles",
						},
						{
							category: "pass",
							displayName: "VIP Passes",
						},
						{
							category: "weapons",
							displayName: "Weapons",
						},
						{
							category: "emote",
							displayName: "Emotes",
						},
						{
							category: "footstep",
							displayName: "Footsteps",
						},
					],
					officialWebsite: "https://bigtime.gg/",
				},
				createdAt: "2022-09-18T22:55:45.061Z",
				updatedAt: "2022-09-18T22:55:45.061Z",
				version: 1,
				slug: "big-time",
			},
			sellableAt: 1665697552833,
			extra: {},
		},
		{
			id: "b4367d80-bc7a-4cd1-b7d9-2ebacc4594ef",
			userId: "9da13787-7509-4a83-9b0c-53b73acf4c6a",
			issuedId: 360,
			collection: "BT0",
			optionName: "space_mythic_small_0",
			status: "unlocked",
			name: "Mythic Small SPACE",
			description:
				"SPACE are expansions to your Personal Metaverse that come in different sizes and rarities. SPACE is needed to attach Utility NFTs such as Armories, Forges and Time Wardens that allow you to craft and upgrade cosmetic NFTs and Hourglasses. SPACE can also be decorated with NFTs that you will find in game. You can connect multiple SPACE together to customize the layout of your Personal Metaverse. A Small Mythic SPACE has 2 Exits that can be used to connect to other SPACE or Utility NFTs.",
			rarity: "mythic",
			imageUrl: "https://openloot-metadata.bigtime.gg/BT0/space_mythic_small_0.png",
			tags: ["space", "mythic", "small"],
			archetypeId: "BT0_space_mythic_small_0",
			archetypeParams: "0",
			maxIssuance: 26400,
			game: {
				id: "56a149cf-f146-487a-8a1c-58dc9ff3a15c",
				name: "Big Time",
				description:
					"Big Time is a free-to-play, multiplayer action RPG game that combines fast-action combat and adventure through time and space.",
				status: "active",
				extra: {
					developer: "Big Time Studios",
					discordUrl: "https://discord.com/invite/bigtime",
					supportUrl: "https://bigtimestudios.zendesk.com/",
					twitterUrl: "https://twitter.com/playbigtime",
					itemCategories: [
						{
							category: "armor",
							displayName: "Armor",
						},
						{
							category: "decorations",
							displayName: "Decorations",
						},
						{
							category: "mysterybox",
							displayName: "Mystery Boxes",
						},
						{
							category: "space",
							displayName: "SPACE",
						},
						{
							category: "title",
							displayName: "Titles",
						},
						{
							category: "pass",
							displayName: "VIP Passes",
						},
						{
							category: "weapons",
							displayName: "Weapons",
						},
						{
							category: "emote",
							displayName: "Emotes",
						},
						{
							category: "footstep",
							displayName: "Footsteps",
						},
					],
					officialWebsite: "https://bigtime.gg/",
				},
				createdAt: "2022-09-18T22:55:45.061Z",
				updatedAt: "2022-09-18T22:55:45.061Z",
				version: 1,
				slug: "big-time",
			},
			sellableAt: 1665697552833,
			extra: {},
		},
		{
			id: "20db738b-c01d-4247-92d5-c277ab3bf60b",
			userId: "9da13787-7509-4a83-9b0c-53b73acf4c6a",
			issuedId: 2693,
			collection: "BT0",
			optionName: "Jade_2H_Sword",
			status: "unlocked",
			name: "Great Sword of Sir Tristram",
			description: "Weapon of Sir Tristram known as the Sad Knight.",
			rarity: "uncommon",
			imageUrl: "https://openloot-metadata.bigtime.gg/BT0/Jade_2H_sword.png",
			tags: ["cosmetic", "jade", "weapons", "greatsword"],
			archetypeId: "BT0_Jade_2H_Sword",
			archetypeParams: "0",
			maxIssuance: 3500,
			game: {
				id: "56a149cf-f146-487a-8a1c-58dc9ff3a15c",
				name: "Big Time",
				description:
					"Big Time is a free-to-play, multiplayer action RPG game that combines fast-action combat and adventure through time and space.",
				status: "active",
				extra: {
					developer: "Big Time Studios",
					discordUrl: "https://discord.com/invite/bigtime",
					supportUrl: "https://bigtimestudios.zendesk.com/",
					twitterUrl: "https://twitter.com/playbigtime",
					itemCategories: [
						{
							category: "armor",
							displayName: "Armor",
						},
						{
							category: "decorations",
							displayName: "Decorations",
						},
						{
							category: "mysterybox",
							displayName: "Mystery Boxes",
						},
						{
							category: "space",
							displayName: "SPACE",
						},
						{
							category: "title",
							displayName: "Titles",
						},
						{
							category: "pass",
							displayName: "VIP Passes",
						},
						{
							category: "weapons",
							displayName: "Weapons",
						},
						{
							category: "emote",
							displayName: "Emotes",
						},
						{
							category: "footstep",
							displayName: "Footsteps",
						},
					],
					officialWebsite: "https://bigtime.gg/",
				},
				createdAt: "2022-09-18T22:55:45.061Z",
				updatedAt: "2022-09-18T22:55:45.061Z",
				version: 1,
				slug: "big-time",
			},
			sellableAt: 1665697552833,
			extra: {},
		},
		{
			id: "ca7a946b-5e44-4c10-ab87-477ba0238974",
			userId: "9da13787-7509-4a83-9b0c-53b73acf4c6a",
			issuedId: 2665,
			collection: "BT0",
			optionName: "Jade_2H_Sword",
			status: "unlocked",
			name: "Great Sword of Sir Tristram",
			description: "Weapon of Sir Tristram known as the Sad Knight.",
			rarity: "uncommon",
			imageUrl: "https://openloot-metadata.bigtime.gg/BT0/Jade_2H_sword.png",
			tags: ["cosmetic", "jade", "weapons", "greatsword"],
			archetypeId: "BT0_Jade_2H_Sword",
			archetypeParams: "0",
			maxIssuance: 3500,
			game: {
				id: "56a149cf-f146-487a-8a1c-58dc9ff3a15c",
				name: "Big Time",
				description:
					"Big Time is a free-to-play, multiplayer action RPG game that combines fast-action combat and adventure through time and space.",
				status: "active",
				extra: {
					developer: "Big Time Studios",
					discordUrl: "https://discord.com/invite/bigtime",
					supportUrl: "https://bigtimestudios.zendesk.com/",
					twitterUrl: "https://twitter.com/playbigtime",
					itemCategories: [
						{
							category: "armor",
							displayName: "Armor",
						},
						{
							category: "decorations",
							displayName: "Decorations",
						},
						{
							category: "mysterybox",
							displayName: "Mystery Boxes",
						},
						{
							category: "space",
							displayName: "SPACE",
						},
						{
							category: "title",
							displayName: "Titles",
						},
						{
							category: "pass",
							displayName: "VIP Passes",
						},
						{
							category: "weapons",
							displayName: "Weapons",
						},
						{
							category: "emote",
							displayName: "Emotes",
						},
						{
							category: "footstep",
							displayName: "Footsteps",
						},
					],
					officialWebsite: "https://bigtime.gg/",
				},
				createdAt: "2022-09-18T22:55:45.061Z",
				updatedAt: "2022-09-18T22:55:45.061Z",
				version: 1,
				slug: "big-time",
			},
			sellableAt: 1665697552833,
			extra: {},
		},
		{
			id: "59286e3a-4801-40a4-9b80-fc4e05642a3d",
			userId: "9da13787-7509-4a83-9b0c-53b73acf4c6a",
			issuedId: 320,
			collection: "BT0",
			optionName: "SuperPink_Title",
			status: "in-game",
			name: "The Laughing Knight",
			description: "Title of Sir Dagonet known as the Laughing Knight.",
			rarity: "epic",
			imageUrl: "https://openloot-metadata.bigtime.gg/BT0/SuperPink_Title.png",
			tags: ["cosmetic", "superpink", "title"],
			archetypeId: "BT0_SuperPink_Title",
			archetypeParams: "0",
			maxIssuance: 350,
			game: {
				id: "56a149cf-f146-487a-8a1c-58dc9ff3a15c",
				name: "Big Time",
				description:
					"Big Time is a free-to-play, multiplayer action RPG game that combines fast-action combat and adventure through time and space.",
				status: "active",
				extra: {
					developer: "Big Time Studios",
					discordUrl: "https://discord.com/invite/bigtime",
					supportUrl: "https://bigtimestudios.zendesk.com/",
					twitterUrl: "https://twitter.com/playbigtime",
					itemCategories: [
						{
							category: "armor",
							displayName: "Armor",
						},
						{
							category: "decorations",
							displayName: "Decorations",
						},
						{
							category: "mysterybox",
							displayName: "Mystery Boxes",
						},
						{
							category: "space",
							displayName: "SPACE",
						},
						{
							category: "title",
							displayName: "Titles",
						},
						{
							category: "pass",
							displayName: "VIP Passes",
						},
						{
							category: "weapons",
							displayName: "Weapons",
						},
						{
							category: "emote",
							displayName: "Emotes",
						},
						{
							category: "footstep",
							displayName: "Footsteps",
						},
					],
					officialWebsite: "https://bigtime.gg/",
				},
				createdAt: "2022-09-18T22:55:45.061Z",
				updatedAt: "2022-09-18T22:55:45.061Z",
				version: 1,
				slug: "big-time",
			},
			sellableAt: 1665697552833,
			extra: {},
		},
		{
			id: "4052b36a-ec4f-4517-b2dc-24261715504e",
			userId: "9b166a48-369f-41bc-ade9-ed6e39d48fe8",
			issuedId: 175,
			collection: "BT0",
			optionName: "Deco_Evermore_Terrarium01",
			status: "unlocked",
			name: "Evermore Large Terrarium",
			description: "A beautiful terrarium that houses flora from various exotic locales",
			rarity: "epic",
			imageUrl: "https://openloot-metadata.bigtime.gg/BT0/Deco_Evermore_Terrarium01.png",
			tags: ["decorations", "evermore", "terrarium"],
			archetypeId: "BT0_Deco_Evermore_Terrarium01",
			archetypeParams: "0",
			maxIssuance: 350,
			game: {
				id: "56a149cf-f146-487a-8a1c-58dc9ff3a15c",
				name: "Big Time",
				description:
					"Big Time is a free-to-play, multiplayer action RPG game that combines fast-action combat and adventure through time and space.",
				status: "active",
				extra: {
					developer: "Big Time Studios",
					discordUrl: "https://discord.com/invite/bigtime",
					supportUrl: "https://bigtimestudios.zendesk.com/",
					twitterUrl: "https://twitter.com/playbigtime",
					itemCategories: [
						{ category: "armor", displayName: "Armor" },
						{ category: "decorations", displayName: "Decorations" },
						{ category: "mysterybox", displayName: "Mystery Boxes" },
						{ category: "space", displayName: "SPACE" },
						{ category: "title", displayName: "Titles" },
						{ category: "pass", displayName: "VIP Passes" },
						{ category: "weapons", displayName: "Weapons" },
						{ category: "emote", displayName: "Emotes" },
						{ category: "footstep", displayName: "Footsteps" },
					],
					officialWebsite: "https://bigtime.gg/",
				},
				createdAt: "2022-09-18T22:55:45.061Z",
				updatedAt: "2022-09-18T22:55:45.061Z",
				version: 1,
				slug: "big-time",
			},
			sellableAt: 1671056987058,
			extra: {},
		},
		{
			id: "8e4fefb6-147d-44b2-8d1c-3df3c5266a38",
			userId: "9da13787-7509-4a83-9b0c-53b73acf4c6a",
			issuedId: 934,
			collection: "BT0",
			optionName: "Jade_2H_Sword",
			status: "unlocked",
			name: "Great Sword of Sir Tristram",
			description: "Weapon of Sir Tristram known as the Sad Knight.",
			rarity: "uncommon",
			imageUrl: "https://openloot-metadata.bigtime.gg/BT0/Jade_2H_sword.png",
			tags: ["cosmetic", "jade", "weapons", "greatsword"],
			archetypeId: "BT0_Jade_2H_Sword",
			archetypeParams: "0",
			maxIssuance: 3500,
			game: {
				id: "56a149cf-f146-487a-8a1c-58dc9ff3a15c",
				name: "Big Time",
				description:
					"Big Time is a free-to-play, multiplayer action RPG game that combines fast-action combat and adventure through time and space.",
				status: "active",
				extra: {
					developer: "Big Time Studios",
					discordUrl: "https://discord.com/invite/bigtime",
					supportUrl: "https://bigtimestudios.zendesk.com/",
					twitterUrl: "https://twitter.com/playbigtime",
					itemCategories: [
						{
							category: "armor",
							displayName: "Armor",
						},
						{
							category: "decorations",
							displayName: "Decorations",
						},
						{
							category: "mysterybox",
							displayName: "Mystery Boxes",
						},
						{
							category: "space",
							displayName: "SPACE",
						},
						{
							category: "title",
							displayName: "Titles",
						},
						{
							category: "pass",
							displayName: "VIP Passes",
						},
						{
							category: "weapons",
							displayName: "Weapons",
						},
						{
							category: "emote",
							displayName: "Emotes",
						},
						{
							category: "footstep",
							displayName: "Footsteps",
						},
					],
					officialWebsite: "https://bigtime.gg/",
				},
				createdAt: "2022-09-18T22:55:45.061Z",
				updatedAt: "2022-09-18T22:55:45.061Z",
				version: 1,
				slug: "big-time",
			},
			sellableAt: 1665697552833,
			extra: {},
		},
		{
			id: "cedf49bd-9865-41a0-b91f-b17b56bff877",
			userId: "9da13787-7509-4a83-9b0c-53b73acf4c6a",
			issuedId: 3304,
			collection: "BT0",
			optionName: "MysteryBox_EarlyAccess_TimeWarden",
			status: "unlocked",
			name: "Time Warden Mystery Box",
			description:
				"A Time Warden Mystery Box that contains 3 Time Warden of rarity from Legendary to Transcendent.  \n**[Read more here.](https://wiki.bigtime.gg/big-time-economy/utility-collectibles-mystery-boxes)**",
			rarity: "uncommon",
			imageUrl: "https://openloot-metadata.bigtime.gg/BT0/MysteryBox_EarlyAccess_TimeWarden.png",
			tags: ["mysterybox", "earlyaccess", "timewarden"],
			archetypeId: "BT0_MysteryBox_EarlyAccess_TimeWarden",
			archetypeParams: "0",
			maxIssuance: 3500,
			game: {
				id: "56a149cf-f146-487a-8a1c-58dc9ff3a15c",
				name: "Big Time",
				description:
					"Big Time is a free-to-play, multiplayer action RPG game that combines fast-action combat and adventure through time and space.",
				status: "active",
				extra: {
					developer: "Big Time Studios",
					discordUrl: "https://discord.com/invite/bigtime",
					supportUrl: "https://bigtimestudios.zendesk.com/",
					twitterUrl: "https://twitter.com/playbigtime",
					itemCategories: [
						{
							category: "armor",
							displayName: "Armor",
						},
						{
							category: "decorations",
							displayName: "Decorations",
						},
						{
							category: "mysterybox",
							displayName: "Mystery Boxes",
						},
						{
							category: "space",
							displayName: "SPACE",
						},
						{
							category: "title",
							displayName: "Titles",
						},
						{
							category: "pass",
							displayName: "VIP Passes",
						},
						{
							category: "weapons",
							displayName: "Weapons",
						},
						{
							category: "emote",
							displayName: "Emotes",
						},
						{
							category: "footstep",
							displayName: "Footsteps",
						},
					],
					officialWebsite: "https://bigtime.gg/",
				},
				createdAt: "2022-09-18T22:55:45.061Z",
				updatedAt: "2022-09-18T22:55:45.061Z",
				version: 1,
				slug: "big-time",
			},
			sellableAt: 1665697552833,
			extra: {},
		},
		{
			id: "cd909882-57bd-4faf-95a4-afe1c3c8d1f4",
			userId: "9da13787-7509-4a83-9b0c-53b73acf4c6a",
			issuedId: 1149,
			collection: "BT0",
			optionName: "space_legendary_medium_0",
			status: "unlocked",
			name: "Legendary Medium SPACE",
			description:
				"SPACE are expansions to your Personal Metaverse that come in different sizes and rarities. SPACE is needed to attach Utility NFTs such as Armories, Forges and Time Wardens that allow you to craft and upgrade cosmetic NFTs and Hourglasses. SPACE can also be decorated with NFTs that you will find in game. You can connect multiple SPACE together to customize the layout of your Personal Metaverse. A Medium Legendary SPACE has 3 Exits that can be used to connect to other SPACE or Utility NFTs.",
			rarity: "legendary",
			imageUrl: "https://openloot-metadata.bigtime.gg/BT0/space_legendary_medium_0.png",
			tags: ["space", "legendary", "medium"],
			archetypeId: "BT0_space_legendary_medium_0",
			archetypeParams: "0",
			maxIssuance: 36000,
			game: {
				id: "56a149cf-f146-487a-8a1c-58dc9ff3a15c",
				name: "Big Time",
				description:
					"Big Time is a free-to-play, multiplayer action RPG game that combines fast-action combat and adventure through time and space.",
				status: "active",
				extra: {
					developer: "Big Time Studios",
					discordUrl: "https://discord.com/invite/bigtime",
					supportUrl: "https://bigtimestudios.zendesk.com/",
					twitterUrl: "https://twitter.com/playbigtime",
					itemCategories: [
						{
							category: "armor",
							displayName: "Armor",
						},
						{
							category: "decorations",
							displayName: "Decorations",
						},
						{
							category: "mysterybox",
							displayName: "Mystery Boxes",
						},
						{
							category: "space",
							displayName: "SPACE",
						},
						{
							category: "title",
							displayName: "Titles",
						},
						{
							category: "pass",
							displayName: "VIP Passes",
						},
						{
							category: "weapons",
							displayName: "Weapons",
						},
						{
							category: "emote",
							displayName: "Emotes",
						},
						{
							category: "footstep",
							displayName: "Footsteps",
						},
					],
					officialWebsite: "https://bigtime.gg/",
				},
				createdAt: "2022-09-18T22:55:45.061Z",
				updatedAt: "2022-09-18T22:55:45.061Z",
				version: 1,
				slug: "big-time",
			},
			sellableAt: 1665697552833,
			extra: {},
		},
		{
			id: "3dc454f2-5437-4b40-ab33-1682bc9ab1e1",
			userId: "9da13787-7509-4a83-9b0c-53b73acf4c6a",
			issuedId: 846,
			collection: "BT0",
			optionName: "space_epic_small_0",
			status: "unlocked",
			name: "Epic Small SPACE",
			description:
				"SPACE are expansions to your Personal Metaverse that come in different sizes and rarities. SPACE is needed to attach Utility NFTs such as Armories, Forges and Time Wardens that allow you to craft and upgrade cosmetic NFTs and Hourglasses. SPACE can also be decorated with NFTs that you will find in game. You can connect multiple SPACE together to customize the layout of your Personal Metaverse. A Small Epic SPACE has 2 Exits that can be used to connect to other SPACE or Utility NFTs.",
			rarity: "epic",
			imageUrl: "https://openloot-metadata.bigtime.gg/BT0/space_epic_small_0.png",
			tags: ["space", "epic", "small"],
			archetypeId: "BT0_space_epic_small_0",
			archetypeParams: "0",
			maxIssuance: 108000,
			game: {
				id: "56a149cf-f146-487a-8a1c-58dc9ff3a15c",
				name: "Big Time",
				description:
					"Big Time is a free-to-play, multiplayer action RPG game that combines fast-action combat and adventure through time and space.",
				status: "active",
				extra: {
					developer: "Big Time Studios",
					discordUrl: "https://discord.com/invite/bigtime",
					supportUrl: "https://bigtimestudios.zendesk.com/",
					twitterUrl: "https://twitter.com/playbigtime",
					itemCategories: [
						{
							category: "armor",
							displayName: "Armor",
						},
						{
							category: "decorations",
							displayName: "Decorations",
						},
						{
							category: "mysterybox",
							displayName: "Mystery Boxes",
						},
						{
							category: "space",
							displayName: "SPACE",
						},
						{
							category: "title",
							displayName: "Titles",
						},
						{
							category: "pass",
							displayName: "VIP Passes",
						},
						{
							category: "weapons",
							displayName: "Weapons",
						},
						{
							category: "emote",
							displayName: "Emotes",
						},
						{
							category: "footstep",
							displayName: "Footsteps",
						},
					],
					officialWebsite: "https://bigtime.gg/",
				},
				createdAt: "2022-09-18T22:55:45.061Z",
				updatedAt: "2022-09-18T22:55:45.061Z",
				version: 1,
				slug: "big-time",
			},
			sellableAt: 1665697552833,
			extra: {},
		},
		{
			id: "cb67d28c-d70f-44a8-9317-67e6c08ed4d4",
			userId: "9da13787-7509-4a83-9b0c-53b73acf4c6a",
			issuedId: 422,
			collection: "BT0",
			optionName: "FixerSingleEye_Legs",
			status: "in-game",
			name: "Apprentice Prototype Legs",
			description: "Early Prototype Fixer Armor designed by Ben Franklin at Evermore.",
			rarity: "rare",
			imageUrl: "https://openloot-metadata.bigtime.gg/BT0/FixerSingleEye_Legs.png",
			tags: ["cosmetic", "fixersingleeye", "armor", "legs"],
			archetypeId: "BT0_FixerSingleEye_Legs",
			archetypeParams: "0",
			maxIssuance: 1000,
			game: {
				id: "56a149cf-f146-487a-8a1c-58dc9ff3a15c",
				name: "Big Time",
				description:
					"Big Time is a free-to-play, multiplayer action RPG game that combines fast-action combat and adventure through time and space.",
				status: "active",
				extra: {
					developer: "Big Time Studios",
					discordUrl: "https://discord.com/invite/bigtime",
					supportUrl: "https://bigtimestudios.zendesk.com/",
					twitterUrl: "https://twitter.com/playbigtime",
					itemCategories: [
						{
							category: "armor",
							displayName: "Armor",
						},
						{
							category: "decorations",
							displayName: "Decorations",
						},
						{
							category: "mysterybox",
							displayName: "Mystery Boxes",
						},
						{
							category: "space",
							displayName: "SPACE",
						},
						{
							category: "title",
							displayName: "Titles",
						},
						{
							category: "pass",
							displayName: "VIP Passes",
						},
						{
							category: "weapons",
							displayName: "Weapons",
						},
						{
							category: "emote",
							displayName: "Emotes",
						},
						{
							category: "footstep",
							displayName: "Footsteps",
						},
					],
					officialWebsite: "https://bigtime.gg/",
				},
				createdAt: "2022-09-18T22:55:45.061Z",
				updatedAt: "2022-09-18T22:55:45.061Z",
				version: 1,
				slug: "big-time",
			},
			sellableAt: 1665697552833,
			extra: {},
		},
		{
			id: "52451d0f-f160-43a6-a9eb-b293aaa87e44",
			userId: "9da13787-7509-4a83-9b0c-53b73acf4c6a",
			issuedId: 142,
			collection: "BT0",
			optionName: "Weaver_2H_Sword",
			status: "unlocked",
			name: "Great Sword of Sir Pellinore",
			description: "Weapon of Sir Pellinore known as the Gentle Knight.",
			rarity: "rare",
			imageUrl: "https://openloot-metadata.bigtime.gg/BT0/Weaver_2H_sword.png",
			tags: ["cosmetic", "weaver", "weapons", "greatsword"],
			archetypeId: "BT0_Weaver_2H_Sword",
			archetypeParams: "0",
			maxIssuance: 1000,
			game: {
				id: "56a149cf-f146-487a-8a1c-58dc9ff3a15c",
				name: "Big Time",
				description:
					"Big Time is a free-to-play, multiplayer action RPG game that combines fast-action combat and adventure through time and space.",
				status: "active",
				extra: {
					developer: "Big Time Studios",
					discordUrl: "https://discord.com/invite/bigtime",
					supportUrl: "https://bigtimestudios.zendesk.com/",
					twitterUrl: "https://twitter.com/playbigtime",
					itemCategories: [
						{
							category: "armor",
							displayName: "Armor",
						},
						{
							category: "decorations",
							displayName: "Decorations",
						},
						{
							category: "mysterybox",
							displayName: "Mystery Boxes",
						},
						{
							category: "space",
							displayName: "SPACE",
						},
						{
							category: "title",
							displayName: "Titles",
						},
						{
							category: "pass",
							displayName: "VIP Passes",
						},
						{
							category: "weapons",
							displayName: "Weapons",
						},
						{
							category: "emote",
							displayName: "Emotes",
						},
						{
							category: "footstep",
							displayName: "Footsteps",
						},
					],
					officialWebsite: "https://bigtime.gg/",
				},
				createdAt: "2022-09-18T22:55:45.061Z",
				updatedAt: "2022-09-18T22:55:45.061Z",
				version: 1,
				slug: "big-time",
			},
			sellableAt: 1665697552833,
			extra: {},
		},
		{
			id: "6ccf58d7-f039-4e8c-86fd-422264022a9c",
			userId: "9da13787-7509-4a83-9b0c-53b73acf4c6a",
			issuedId: 3226,
			collection: "BT0",
			optionName: "Title_ASilverLining",
			status: "unlocked",
			name: "A Silver Lining",
			description: "Behind the stormclouds, bright sunshine awaits.",
			rarity: "uncommon",
			imageUrl: "https://openloot-metadata.bigtime.gg/BT0/Title_ASilverLining.png",
			tags: ["cosmetic", "title"],
			archetypeId: "BT0_Title_ASilverLining",
			archetypeParams: "0",
			maxIssuance: 3500,
			game: {
				id: "56a149cf-f146-487a-8a1c-58dc9ff3a15c",
				name: "Big Time",
				description:
					"Big Time is a free-to-play, multiplayer action RPG game that combines fast-action combat and adventure through time and space.",
				status: "active",
				extra: {
					developer: "Big Time Studios",
					discordUrl: "https://discord.com/invite/bigtime",
					supportUrl: "https://bigtimestudios.zendesk.com/",
					twitterUrl: "https://twitter.com/playbigtime",
					itemCategories: [
						{
							category: "armor",
							displayName: "Armor",
						},
						{
							category: "decorations",
							displayName: "Decorations",
						},
						{
							category: "mysterybox",
							displayName: "Mystery Boxes",
						},
						{
							category: "space",
							displayName: "SPACE",
						},
						{
							category: "title",
							displayName: "Titles",
						},
						{
							category: "pass",
							displayName: "VIP Passes",
						},
						{
							category: "weapons",
							displayName: "Weapons",
						},
						{
							category: "emote",
							displayName: "Emotes",
						},
						{
							category: "footstep",
							displayName: "Footsteps",
						},
					],
					officialWebsite: "https://bigtime.gg/",
				},
				createdAt: "2022-09-18T22:55:45.061Z",
				updatedAt: "2022-09-18T22:55:45.061Z",
				version: 1,
				slug: "big-time",
			},
			sellableAt: 1665697552833,
			extra: {},
		},
	],
};

export const localDb: any = _localDb as OpenLootCollection;
